import Dependencies
import Records
import Testing

/// Regression tests for the ring-review R-05 savepoint-identifier hardening:
/// caller-supplied savepoint names are validated and quoted before SQL
/// interpolation; invalid names throw before any SQL executes.
@Suite struct SavepointNameValidationTests {

    /// A writer stub that throws a marker error on first use, proving the
    /// savepoint-name validation ran (or not) before any connection work.
    struct MarkerError: Swift.Error {}

    final class StubWriter: Database.Writer, @unchecked Sendable {
        func read<T: Sendable>(
            _ block:
                @Sendable (any Database.Connection.`Protocol`) async throws(Database.Error) ->
                T
        ) async throws(Database.Error) -> T {
            throw .queryFailed(underlying: MarkerError())
        }

        func write<T: Sendable>(
            _ block:
                @Sendable (any Database.Connection.`Protocol`) async throws(Database.Error) ->
                T
        ) async throws(Database.Error) -> T {
            throw .queryFailed(underlying: MarkerError())
        }

        func close() async throws(Database.Error) {}
    }

    /// Asserts that the writer's marker error surfaced, proving the savepoint
    /// name passed validation and reached the writer.
    private func expectMarker(
        _ body: @Sendable () async throws(Database.Error) -> Void
    ) async {
        do {
            try await body()
            Issue.record("expected the stub marker error to be thrown")
        } catch {
            guard case .queryFailed(let underlying) = error, underlying is MarkerError else {
                Issue.record("expected the stub marker error, got \(error)")
                return
            }
        }
    }

    @Test func injectionShapedNameThrowsBeforeAnySQL() async {
        let writer = StubWriter()
        await #expect(throws: Database.Error.self) {
            try await writer.withSavepoint(#"sp"; DROP TABLE users; --"#) { _ in }
        }
    }

    @Test func embeddedQuoteThrows() async {
        let writer = StubWriter()
        await #expect(throws: Database.Error.self) {
            try await writer.withSavepoint(#"sp""escape"#) { _ in }
        }
    }

    @Test func emptyNameThrows() async {
        let writer = StubWriter()
        await #expect(throws: Database.Error.self) {
            try await writer.withSavepoint("") { _ in }
        }
    }

    @Test func overlongNameThrows() async {
        let writer = StubWriter()
        let name = String(repeating: "a", count: 64)
        await #expect(throws: Database.Error.self) {
            try await writer.withSavepoint(name) { _ in }
        }
    }

    @Test func validNameReachesTheWriter() async {
        // A valid name passes validation and proceeds to the writer,
        // which throws the marker — proving validation did not reject it.
        let writer = StubWriter()
        await expectMarker {
            try await writer.withSavepoint("critical_update-1") { _ in }
        }
    }

    @Test func autoGeneratedNamePassesValidation() async {
        let writer = StubWriter()
        await expectMarker {
            try await writer.withSavepoint { _ in }
        }
    }
}
